[build]
  command = "npm install"
  publish = "."  # this must not point to "dist" if you don't use a build output

[functions]
  directory = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
